//listings
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$collection = $productCollection->create()->addAttributeToSelect('*')->load();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStoreId = $storeManager->getStore()->getId();
$rating = $objectManager->get("Magento\Review\Model\ResourceModel\Review\CollectionFactory");
//== get product collection
?>
<div class="our_testimoni">
    <div class="mid_container">
        <div class="content-heading">
            <h2 class="title">Testimonials</h2>
        </div>
        <div id="owl-testimonial" class="owl-carousel">
        <?php    
        foreach ($collection as $product){ //echo 'Name = '.$product->getId().'<br>';
            $reviewcollection = $rating->create()->addStoreFilter( $currentStoreId )
                                    ->addStatusFilter( \Magento\Review\Model\Review::STATUS_APPROVED )
                                    ->addEntityFilter( 'product', $product->getId() )->setDateOrder();
            //echo "<pre>"; print_r($reviewcollection->getData());
            //loop through review collection
            foreach($reviewcollection as $review){ //print_r($review->getData()); 
           ?>
            
            <div class="item"> 
             
                <?php
                  $timestamp = strtotime($review['created_at']); 
                 ?>
                    <span class="testi_image"></span>
                    <div class="details"><?php echo $review['detail']; ?></div>
                    <div class="nickname"> <?php echo $review['nickname'];?> </div>
                    <div class="datep"><?php echo date("M Y", $timestamp);?></div>
            </div>   
           <?php } ?>

           
            <?php    
            }
            ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#owl-testimonial": {
            "OwlCarousel": {
                "navigation" : false,
                "pagination": false,    
                "autoPlay": 3000,
                "items": 1,
                "itemsDesktop": [1199, 3],
                "itemsDesktopSmall": [979, 3]
            }
        }
    }
</script>
===============================
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$collection = $productCollection->create()->addAttributeToSelect('*')->load();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStoreId = $storeManager->getStore()->getId();
$rating = $objectManager->get("Magento\Review\Model\ResourceModel\Review\CollectionFactory");
//== get product collection
?>
<div class="our_testimoni">
    <div class="mid_container">
        
        <div class="testinner">
        <?php
        $i=1;
        foreach ($collection as $product){ //echo 'Name = '.$product->getId().'<br>';
            $reviewcollection = $rating->create()->addStoreFilter( $currentStoreId )
                                    ->addStatusFilter( \Magento\Review\Model\Review::STATUS_APPROVED )
                                    ->addEntityFilter( 'product', $product->getId() )->setDateOrder();
            //echo "<pre>"; print_r($reviewcollection->getData());
            //loop through review collection
            
             if($i==10)
                {
                    break;
                }
            foreach($reviewcollection as $review){ //print_r($review->getData()); 
               
           ?>
            
            <div class="item"> 
             
                <?php
                  $timestamp = strtotime($review['created_at']); 
                 ?>
                    <span class="testi_image"></span>
                    <div class="desc_sec">
                        <div class="details"><?php echo $review['detail']; ?></div>
                        <div class="nickname"> <?php echo $review['nickname'];?> </div>
                        <div class="datep"><?php echo date("M Y", $timestamp);?></div>
                    </div>
            </div>   
           <?php  } ?>

           
            <?php  
            $i++;
            }
            ?>
        </div>
    </div>
</div>
